spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: 5547
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: * # TODO exposure all endpoints of actuator only in development environment

offers:
  discount: 590%