spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: 5547
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8002

config:
  text: "development environment"
  author:
    name: "Steven"
    email: "steven@gmail.com"